server {
    listen 80;
    server_name _;

    root /usr/share/nginx/html;
    index index.html;

    location /api/endorsement/ {
        proxy_pass http://endorsement:8080/;
        proxy_set_header Host $host;
        proxy_set_header X-Request-Id $request_id;
    }

    location /api/routing/ {
        proxy_pass http://routing:8081/;
        proxy_set_header Host $host;
        proxy_set_header X-Request-Id $request_id;
    }

    location / {
        try_files $uri /index.html;
    }
}
